// Generated by CoffeeScript 2.3.1
(function() {
  var assert, computeEligibility;

  assert = require("chai").assert;

  computeEligibility = require("../src/insurance");

  /*
    note "XXX" in inputs means the value is irrelevant to the decision process
    in reality you would probably not pass ANY value in - depending on how the coder designed the system
  */
  describe("Insurance Company Flotation", function() {
    return describe("Eligibility Calcs", function() {
      // the big split
      describe("Current Policy Holder", function() {
        it("should offer shares : full benefits", function() {
          return assert(computeEligibility(true, true, true), "eligibleForShares");
        });
        it("should return cash only : not since 2001", function() {
          return assert(computeEligibility(true, true, false), "eligibleForCash");
        });
        return it("should return notEligible - not 'with benefits' policy", function() {
          return assert(computeEligibility(true, false, "XXX"), "notEligible");
        });
      });
      return describe("Not A Current Policy Holder", function() {
        return it("should return notEligible - not current policyholder", function() {
          return assert(computeEligibility(false, "XXX", "XXX"), "notEligible");
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=insurance.js.map
