// Generated by CoffeeScript 2.3.1
(function() {
  var Supermarket, assert;

  assert = require("chai").assert;

  Supermarket = require("../src/supermarket");

  describe("Supermarket", function() {
    return describe("Simple Transaction", function() {
      // generate the 4 test cases
      describe("Loyalty Card Holders", function() {
        var isLoyaltyCardHolder;
        isLoyaltyCardHolder = true;
        it("should return extraDiscount : loyalty card holder, prefers discount", function() {
          return assert(Supermarket.processTransaction("XXX", isLoyaltyCardHolder, true), "extraDiscount");
        });
        return it("should return points : loyalty card holder, point preferred", function() {
          return assert(Supermarket.processTransaction("XXX", isLoyaltyCardHolder, false), "points");
        });
      });
      return describe("Cash Customers", function() {
        var isLoyaltyCardHolder;
        isLoyaltyCardHolder = false;
        it("should return noDiscount : spend <= 100 ", function() {
          return assert(Supermarket.processTransaction(100, isLoyaltyCardHolder, "XXX"), "noDiscount");
        });
        return it("should return discount : spend > 100", function() {
          return assert(Supermarket.processTransaction(101, isLoyaltyCardHolder, "XXX"), "discount");
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=supermarket.js.map
